# Generated by Django 4.1.2 on 2022-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('facebook_link', models.URLField(max_length=100)),
                ('twiter_link', models.URLField(max_length=100)),
                ('googleplus_link', models.URLField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
